#!/bin/sh
#
# Usage: get-scala-revision [dir]
# Figures out current scala revision of an svn checkout or
# a git-svn mirror (or a git clone.)
#
# If no dir is given, current working dir is used.

DIR=""
if [ $# -eq 0 ]; then
  DIR=`pwd`
else
  DIR=$1
fi

cd $DIR

#scalagwt uses git
git describe --always
